name: Missing URL report
description: File a report for a missing URL
title: "[Missing]: "
labels: ["bug"]
assignees: ["maxmakesmagic"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a report for a missing URL! Please fill out the following information to help resolve the issue.
  - type: input
    id: url
    attributes:
      label: URL
      description: The URL that is missing
      placeholder: https://magic.wizards.com
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of the plugin that you are using
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Any additional information that you think would be helpful
