name: Publish

on:
  push:
    tags:
      - "*"

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Make and publish webextension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./make_extension.sh

      # Upload and release only on tags
      - name: Upload & release to Chrome
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: deekay.zip
          extension-id: ${{ secrets.EXTENSION_ID}}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')

      # Always upload the artifact zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deekay
          path: deekay.zip
